 &time_control
 run_days                            = 0,
 run_hours                           = 0,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2011, 2011, 2011,
 start_month                         = 11,   11,   11,  
 start_day                           = 23,   23,   24,
 start_hour                          = 23,   23,   00,
 start_minute                        = 00,   00,   00,
 end_year                            = 2011, 2011, 2011,
 end_month                           = 11,   11,   11,
 end_day                             = 24,   24,   24,
 end_hour                            = 20,   05,   03,
 end_minute                          = 00,   00,   30,
 interval_seconds                    = 3600
 input_from_file                     = .true.,.false.,.false.,
 history_interval_s                  = 300,300,900,
 frames_per_outfile                  = 1, 1, 1,
 restart                             = .true.,
 restart_interval                    = 30,
 override_restart_timers             = .true.,
 io_form_history                     = 13
 io_form_restart                     = 13
 io_form_input                       = 2
 io_form_boundary                    = 2
 nocolons                            = .true.,
 /

 &domains
 time_step                           = 0,
 time_step_fract_num                 = 1,
 time_step_fract_den                 = 2,
 max_dom                             = 3,
 e_we                                = 1300, 1201, 2901,
 e_sn                                = 925,   997, 2301,
 e_vert                              = 232,   232,  232,
 dzstretch_s                         = 1.1
 p_top_requested                     = 500,
 num_metgrid_levels                  = 38,
 num_metgrid_soil_levels             = 4,
 dx                                  = 1600, 400, 100,
 dy                                  = 1600, 400, 100,
 grid_id                             = 1,      2,  3,
 parent_id                           = 0,      1,  2,
 i_parent_start                      = 1,    405,  270,
 j_parent_start                      = 1,    395,  270,
 parent_grid_ratio                   = 1,      4,   4,
 parent_time_step_ratio              = 1,      1,   1,
 feedback                            = 0,
 smooth_option                       = 0,
 wif_input_opt                       = 1,
/

 &physics
 mp_physics                          =  28,   28, 28,
 do_radar_ref                        =  1,
 cu_physics                          =  0,     0,  0,
 shcu_physics                        =  3,     0,  0,
 ra_lw_physics                       =  4,     4,  4,
 ra_sw_physics                       =  4,     4,  4,
 bl_pbl_physics                      =  1,     0,  0,
 topo_wind                           =  1,     0,  0,
 sf_sfclay_physics                   =  1,     1,  1,
 sf_surface_physics                  =  2,     2,  2,
 isfflx                              =  1,
 radt                                =  1,     1,  1,
 bldt                                = 0,     0,   0,
 cudt                                = 0,     0,   0,
 icloud                              = 1,
 num_land_cat                        = 21,
 sf_urban_physics                    = 0,     0,   0,
 fractional_seaice                   = 1,
 /

 &fdda
 /

 &dynamics
 hybrid_opt                          = 2, 
 w_damping                           = 0,
 diff_opt                            = 2,      2,  2,
 km_opt                              = 4,      2,  2,
 sfs_opt                             = 0,      0,  1,
 mix_isotropic                       = 0,      0,  1, 
 diff_6th_opt                        = 0,      0,  0, 
 diff_6th_factor                     = 0.12,   0.12,0.12,
 base_temp                           = 290.
 damp_opt                            = 3,
 zdamp                               = 5000.,  5000.,5000.,
 dampcoef                            = 0.2,    0.2,  0.2,
 khdif                               = 0,      0,    0,
 kvdif                               = 0,      0,    0,
 non_hydrostatic                     = .true., .true.,.true.,
 moist_adv_opt                       = 4,      4,    4,
 scalar_adv_opt                      = 3,      3,    3,
 momentum_adv_opt                    = 1,      1,    1,
 gwd_opt                             = 0,      0,    0,
 mix_full_fields                     = .true., .true.,.true.,
 time_step_sound                     = 0,      0,    0,
 /

 &bdy_control
 spec_bdy_width                      = 5,
 specified                           = .true.
 /

 &grib2
 /

 &namelist_quilt
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /
